name: Bug Report
description: File a bug report
title: "New Internship: "
labels: ["new_internship"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: company_name
    attributes:
      label: Company Name
      description: How can we get in touch with you if we need more info?
      placeholder: ex. Google
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Internship Title
      description: How can we get in touch with you if we need more info?
      placeholder: ex. ML Software Intern
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Link to Internship Posting
      description: How can we get in touch with you if we need more info?
      placeholder: ex. example.com/link/to/posting
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the internship located? (Please enter semicolon-separated list if there are multiple options. Include Remote if remote option available)
      placeholder: San Franciso, CA; Austin, TX; Remote
    validations:
      required: true
